# Clase 23

In [ ]:
import numpy as np
import time

---

### Ejercicio: Integrales definidas y el método del rectángulo

(ver [wikipedia](https://en.wikipedia.org/wiki/Rectangle_method))

El método del rectángulo calcula de manera aproximada una integra definida de una funcíon. Una integral en un intervalo definido
$$
\int_a^b f(x) \mathrm{d}x
$$
puede verse como el área bajo la curva dibujada por la función en el integrando.

<img src="definite-integral.png">

Una aproximación al valor numérico de la integral se puede lograr dividiendo el área bajo la curva en rectángulos para los cuales su área puede ser calculada.

<img src="rectangle_rule.gif">

La aproximación a la integral será entonces la suma de estas pequeñas áreas que se encuentran en el intervalo de integración.

Especificamente, el método del rectangulo para la integral $\int_a^b f(x) \mathrm{d}x$ se formula de la siguiente manera: se divide el intervalo de integración $(a,b)$ en $N$ segmentos iguales de longitud $h=(b-a)/N$, con estos se define un rectangulo de altura $f(x_n)$ y base $h$ y área $A_n = h\, f(x_n)$ donde $x_n=a+n\,h$, de manera que la integral se puede aproximar como 
$$
\int_a^b f(x) \mathrm{d}x \approx \sum_{n=0}^{N-1} h\, f(x_n) = \sum_{n=0}^{N-1} A_n = \frac{b-a}{N}\sum_{n=0}^{N-1} f\left(a+n\,\frac{b-a}{N}\right)
$$

1. Aproxime la integral
$$
\int_0^{\pi/2} \sin(x) \mathrm{d}x 
$$
haciendo uso del método del rectángulo.

In [10]:
import numpy as np
import time


N = 999999   # numero de rectangulos
a = 0       # limite inferior
b = np.pi/2 # limite superior

f = lambda x: np.sin(x)   # funcion a integrar

### Solución usando ciclos ###

t0 = time.time()

suma = 0.0
for i in xrange(0,N):
    suma += f(a+i*(b-a)/N)
    
resultado = (b-a)/N*suma

t1 = time.time()

print resultado
print 'tiempo:',t1-t0
print

### Solución usando arrays de numpy ###

t0 = time.time()

x = np.linspace(a,b,N)
h = (b-a)/N
alturas = np.sin(x)
areas = h*alturas

resultado = areas.sum()

t1 = time.time()

print resultado
print 'tiempo:', t1-t0

0.999999214601
tiempo: 2.41429901123

0.999999785398
tiempo: 0.0307908058167


In [4]:
x = np.linspace?

In [7]:
x = np.linspace(a,b,N)
h = (b-a)/N
alturas = np.sin(x)
areas = h*alturas

areas.sum()

0.99999785393961049

---

## Matrices en numpy

Los arrays creados hasta ahora han sido del tipo `ndarray`. Numpy también tiene un tipo llamado `matrix` o `mat`, que es similar a las estructuras de datos que forman matrices en Matlab. Es decir, un array uno-dimensional es corresponce a un vector fila o un vector columna cuando es convertido en un objeto del tipo `matrix`.

In [11]:
x1 = np.array([1,2,3],float)
x2 = np.matrix(x1)
x2

matrix([[ 1.,  2.,  3.]])

In [12]:
x3 = x2.transpose()
x3

matrix([[ 1.],
        [ 2.],
        [ 3.]])

In [13]:
type(x3)

numpy.matrixlib.defmatrix.matrix

Arrays de dimensión mayor que dos no pueden ser representados como instancias de `matrix`.

La ventaja de los objetos `matrix` es que la multiplicación representa el producto matriz-matriz, matriz-vector, vector-matriz como el que conocemos del álgebra lineal:

In [14]:
A = np.eye(3)       # matriz identidad
A

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
A = np.matrix(A)
A

matrix([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

In [16]:
y2 = x2*A
y2

matrix([[ 1.,  2.,  3.]])

In [17]:
y3 = A*x3
y3

matrix([[ 1.],
        [ 2.],
        [ 3.]])

In [18]:
A*x2

ValueError: matrices are not aligned

Comparemos el profucto de arrays con el producto de matrices

In [19]:
A = (np.zeros(9)+1).reshape(3,3)     # Array 3x3 lleno de 1's
A

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
x1

array([ 1.,  2.,  3.])

In [21]:
A*x1         # [A[0,:]*x1, A[1,:]*x1, A[2,:]*x1]

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [22]:
B = A+1      # Suma elemento a elemento
B

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [23]:
A*B          # Producto elemento a elemento

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [24]:
A = np.matrix(A)
B = np.matrix(B)

A*B          # Producto de matrices

matrix([[ 6.,  6.,  6.],
        [ 6.,  6.,  6.],
        [ 6.,  6.,  6.]])

In [25]:
A*x1         # Producto de matriz y vector

ValueError: matrices are not aligned

---

### Ejercicio

**1. Multiplicación de matrix-vector con arrays de numpy:** Sea $\mathbf{A}$ una matriz cuadrada de dimensión $3\times3$ y $\mathbf{b}$ un vector columna de dimensión $3\times 1$
$$
\mathbf{A} = \begin{pmatrix}
a & b & c \\
p & q & r \\
u & v & w
\end{pmatrix}, \quad \mathbf{b} = \begin{pmatrix}
x \\
y \\
z
\end{pmatrix}\,,
$$

el producto entre ellos estará definido por:

$$\mathbf{Ab} = \begin{pmatrix}
a & b & c \\
p & q & r \\
u & v & w
\end{pmatrix} \begin{pmatrix}
x \\
y \\
z
\end{pmatrix} =\begin{pmatrix}
ax + by + cz \\
px + qy + rz \\
ux + vy + wz
\end{pmatrix}\,.
$$

En general la multiplicación de una matriz $\mathbf{A}$ de dimensión $p\times q$ por un vector columna $\mathbf{b}$ de dimensión $q\times 1$, está definida como 
$$
\mathbf{c}_{i} = \sum_{k=1}^q \mathbf{A}_{i,k}\, \mathbf{b}_k\, ;
$$

escriba un programa en python que, usando numpy y dados una matrix y un vector de la forma
```python
A = array([[1,2,3],[4,5,6],[7,8,9]])
b = array([-3,-2,-1])
```
calcule su multiplicación (i.e., el vector $\mathbf{c}$ para el cual sus componentes son `c[i]`=$\sum_{j=0}^2$`A[i,j]*b[j]`). Luego, usando el módulo `np.matrix` busque la función que calcule el producto estándar entre matriz-vector. Agregue a su código una evaluación del tiempo de ejecucuón y comparelo con el tiempo de ejecución de la operación en el módulo `np.matrix`.

**2. Slicing y multiplicación de matrices:** Extraiga como un slice la matriz $2\times 2$ en la esquina inferior derecha de la matriz $\mathbf{A}$ definida en el problema anterior. Sume este slice con la matriz $2\times 2$ obtenida de la esquina superior izquierda de $\mathbf{A}$, multiplique el resultado por la matriz de la esquina superior derecha e inserte el resultado en la esquina inferior izquierda de la matriz $\mathbf{A}$. Controle los resultados haciendo las cálculos a mano.