# Clase 22

In [7]:
import numpy as np
import time

## Loops sobre arrays

Iterar sobre un array de numpy también se puede lograr usando el ciclo `for`

In [45]:
a = np.zeros((10,10))   # creo un array de 10x10 lleno de ceros

t0 = time.time()
for i in xrange(0,a.shape[0]):                 # el índice i recorre las filas
    for j in xrange(0,a.shape[1]):             # el índice j recorre las columnas
        a[i,j] = (i+1)*(j+1)*(j+2)
        #a.itemset((i,j), (i+1)*(j+1)*(j+2) )  # equivalente a a[i,j] = (i+1)*(j+1)*(j+2)
        print "a[%d,%d]=%g" %(i,j,a[i,j])
    print                                      # nueva línea en cada fila
    
t1 = time.time()

print t1-t0

a[0,0]=2
a[0,1]=6
a[0,2]=12
a[0,3]=20
a[0,4]=30
a[0,5]=42
a[0,6]=56
a[0,7]=72
a[0,8]=90
a[0,9]=110

a[1,0]=4
a[1,1]=12
a[1,2]=24
a[1,3]=40
a[1,4]=60
a[1,5]=84
a[1,6]=112
a[1,7]=144
a[1,8]=180
a[1,9]=220

a[2,0]=6
a[2,1]=18
a[2,2]=36
a[2,3]=60
a[2,4]=90
a[2,5]=126
a[2,6]=168
a[2,7]=216
a[2,8]=270
a[2,9]=330

a[3,0]=8
a[3,1]=24
a[3,2]=48
a[3,3]=80
a[3,4]=120
a[3,5]=168
a[3,6]=224
a[3,7]=288
a[3,8]=360
a[3,9]=440

a[4,0]=10
a[4,1]=30
a[4,2]=60
a[4,3]=100
a[4,4]=150
a[4,5]=210
a[4,6]=280
a[4,7]=360
a[4,8]=450
a[4,9]=550

a[5,0]=12
a[5,1]=36
a[5,2]=72
a[5,3]=120
a[5,4]=180
a[5,5]=252
a[5,6]=336
a[5,7]=432
a[5,8]=540
a[5,9]=660

a[6,0]=14
a[6,1]=42
a[6,2]=84
a[6,3]=140
a[6,4]=210
a[6,5]=294
a[6,6]=392
a[6,7]=504
a[6,8]=630
a[6,9]=770

a[7,0]=16
a[7,1]=48
a[7,2]=96
a[7,3]=160
a[7,4]=240
a[7,5]=336
a[7,6]=448
a[7,7]=576
a[7,8]=720
a[7,9]=880

a[8,0]=18
a[8,1]=54
a[8,2]=108
a[8,3]=180
a[8,4]=270
a[8,5]=378
a[8,6]=504
a[8,7]=648
a[8,8]=810
a[8,9]=990

a[9,0]=20
a[9,1]=60
a[9,2]=120
a[9,3]=200
a[

0.00186896324158    #  a[i,j] = (i+1)*(j+1)*(j+2)
0.00169086456299    #  a.itemset((i,j), (i+1)*(j+1)*(j+2) )
0.000164985656738   # fromfunction

otra forma de lograr lo anterior es usando el la función `np.fromfunction` como vimos en la sesión anterior

In [ ]:
func = lambda i,j: (i+1)*(j+1)*(j+2)   # función que retorna la operación con los índices i,j
t0 = time.time()
a = np.fromfunction(func,(10,10))
t1 = time.time()
print a
print t1-t0

**Pregunta: ** ¿Cuál de los métodos anteriores es más eficiente? Recuerde que con la función `time` del módulo `time`
```python
from time import time
t0 = time.time()
  # aquí el código
t1 = time.time()
print t1-t0
```
puede averiguar el tiempo de ejecución de una serie de comandos. Hágalo para las tres versiones anteriores del código y encuentre cuál es más eficiente.

## Cálculos con arrays

Consideremos el siguiente problema, queremos multiplicar cada elemento de el array `a` por 3 y luego restarle uno; es decir, construir un array `b` tal que sus elementos sean `b[i,j]=3*a[i,j]-1`

---
### Ejercicio
Escriba una función en python que realize la operación anterior para cualquier array que le sea dado como argumento; lo anterior recorriendo todo el array con ciclos `for`.

In [29]:
t0 = time.time()
b = np.zeros_like(a)

for i in xrange(0,a.shape[0]):
    for j in xrange(0,a.shape[1]):
        b[i,j] = 3*a[i,j]-1
    
t1 = time.time()
print b
print t1-t0

[[    5.    17.    35.    59.    89.   125.   167.   215.   269.   329.]
 [   11.    35.    71.   119.   179.   251.   335.   431.   539.   659.]
 [   17.    53.   107.   179.   269.   377.   503.   647.   809.   989.]
 [   23.    71.   143.   239.   359.   503.   671.   863.  1079.  1319.]
 [   29.    89.   179.   299.   449.   629.   839.  1079.  1349.  1649.]
 [   35.   107.   215.   359.   539.   755.  1007.  1295.  1619.  1979.]
 [   41.   125.   251.   419.   629.   881.  1175.  1511.  1889.  2309.]
 [   47.   143.   287.   479.   719.  1007.  1343.  1727.  2159.  2639.]
 [   53.   161.   323.   539.   809.  1133.  1511.  1943.  2429.  2969.]
 [   59.   179.   359.   599.   899.  1259.  1679.  2159.  2699.  3299.]]
0.000416994094849


In [35]:
t0 = time.time()
b = a.copy()

for i in xrange(0,a.shape[0]):
    for j in xrange(0,a.shape[1]):
        b[i,j] = 3*b[i,j]-1
    
t1 = time.time()
print b
print t1-t0

[[    5.    17.    35.    59.    89.   125.   167.   215.   269.   329.]
 [   11.    35.    71.   119.   179.   251.   335.   431.   539.   659.]
 [   17.    53.   107.   179.   269.   377.   503.   647.   809.   989.]
 [   23.    71.   143.   239.   359.   503.   671.   863.  1079.  1319.]
 [   29.    89.   179.   299.   449.   629.   839.  1079.  1349.  1649.]
 [   35.   107.   215.   359.   539.   755.  1007.  1295.  1619.  1979.]
 [   41.   125.   251.   419.   629.   881.  1175.  1511.  1889.  2309.]
 [   47.   143.   287.   479.   719.  1007.  1343.  1727.  2159.  2639.]
 [   53.   161.   323.   539.   809.  1133.  1511.  1943.  2429.  2969.]
 [   59.   179.   359.   599.   899.  1259.  1679.  2159.  2699.  3299.]]
0.000427007675171


---

Numpy ofrece una gran cantidad de funciones eficientes implementadas en C que operan sobre todo el array. La operacion anterior se puede lograr usando el siguiente código:
```python
b = 3*a-1
```
En este caso todos los elementos en `a` son multiplicados por 3 y el resultado es guardado en un array temporal. Luego 1 es substraído de cada uno de los elementos de este array temporal y el resultado se guarda en un nuevo array temporal para el cual `b` se vuelve una referencia.

---
### Ejercicio

Investigue el tiempo de ejecución de la operación anterior para el caso implementado con ciclos y el caso en el que se utiliza la sintaxis de numpy.

In [34]:
t0 = time.time()
b=3*a-1
t1 = time.time()
print b
print t1-t0

[[    5.    17.    35.    59.    89.   125.   167.   215.   269.   329.]
 [   11.    35.    71.   119.   179.   251.   335.   431.   539.   659.]
 [   17.    53.   107.   179.   269.   377.   503.   647.   809.   989.]
 [   23.    71.   143.   239.   359.   503.   671.   863.  1079.  1319.]
 [   29.    89.   179.   299.   449.   629.   839.  1079.  1349.  1649.]
 [   35.   107.   215.   359.   539.   755.  1007.  1295.  1619.  1979.]
 [   41.   125.   251.   419.   629.   881.  1175.  1511.  1889.  2309.]
 [   47.   143.   287.   479.   719.  1007.  1343.  1727.  2159.  2639.]
 [   53.   161.   323.   539.   809.  1133.  1511.  1943.  2429.  2969.]
 [   59.   179.   359.   599.   899.  1259.  1679.  2159.  2699.  3299.]]
0.000100135803223


---

Existe una forma de realizar la misma operación utilizando modificanciones en sitio (*in-place modifications*) de `b`

In [36]:
a

array([[    2.,     6.,    12.,    20.,    30.,    42.,    56.,    72.,
           90.,   110.],
       [    4.,    12.,    24.,    40.,    60.,    84.,   112.,   144.,
          180.,   220.],
       [    6.,    18.,    36.,    60.,    90.,   126.,   168.,   216.,
          270.,   330.],
       [    8.,    24.,    48.,    80.,   120.,   168.,   224.,   288.,
          360.,   440.],
       [   10.,    30.,    60.,   100.,   150.,   210.,   280.,   360.,
          450.,   550.],
       [   12.,    36.,    72.,   120.,   180.,   252.,   336.,   432.,
          540.,   660.],
       [   14.,    42.,    84.,   140.,   210.,   294.,   392.,   504.,
          630.,   770.],
       [   16.,    48.,    96.,   160.,   240.,   336.,   448.,   576.,
          720.,   880.],
       [   18.,    54.,   108.,   180.,   270.,   378.,   504.,   648.,
          810.,   990.],
       [   20.,    60.,   120.,   200.,   300.,   420.,   560.,   720.,
          900.,  1100.]])

In [43]:
t0 = time.time()
b = a
b = np.multiply(b,3,b)
b = np.subtract(b,1,b)
t1 = time.time()
print t1-t0

0.000159978866577


In [38]:
b

array([[    5.,    17.,    35.,    59.,    89.,   125.,   167.,   215.,
          269.,   329.],
       [   11.,    35.,    71.,   119.,   179.,   251.,   335.,   431.,
          539.,   659.],
       [   17.,    53.,   107.,   179.,   269.,   377.,   503.,   647.,
          809.,   989.],
       [   23.,    71.,   143.,   239.,   359.,   503.,   671.,   863.,
         1079.,  1319.],
       [   29.,    89.,   179.,   299.,   449.,   629.,   839.,  1079.,
         1349.,  1649.],
       [   35.,   107.,   215.,   359.,   539.,   755.,  1007.,  1295.,
         1619.,  1979.],
       [   41.,   125.,   251.,   419.,   629.,   881.,  1175.,  1511.,
         1889.,  2309.],
       [   47.,   143.,   287.,   479.,   719.,  1007.,  1343.,  1727.,
         2159.,  2639.],
       [   53.,   161.,   323.,   539.,   809.,  1133.,  1511.,  1943.,
         2429.,  2969.],
       [   59.,   179.,   359.,   599.,   899.,  1259.,  1679.,  2159.,
         2699.,  3299.]])

In [39]:
a

array([[    5.,    17.,    35.,    59.,    89.,   125.,   167.,   215.,
          269.,   329.],
       [   11.,    35.,    71.,   119.,   179.,   251.,   335.,   431.,
          539.,   659.],
       [   17.,    53.,   107.,   179.,   269.,   377.,   503.,   647.,
          809.,   989.],
       [   23.,    71.,   143.,   239.,   359.,   503.,   671.,   863.,
         1079.,  1319.],
       [   29.,    89.,   179.,   299.,   449.,   629.,   839.,  1079.,
         1349.,  1649.],
       [   35.,   107.,   215.,   359.,   539.,   755.,  1007.,  1295.,
         1619.,  1979.],
       [   41.,   125.,   251.,   419.,   629.,   881.,  1175.,  1511.,
         1889.,  2309.],
       [   47.,   143.,   287.,   479.,   719.,  1007.,  1343.,  1727.,
         2159.,  2639.],
       [   53.,   161.,   323.,   539.,   809.,  1133.,  1511.,  1943.,
         2429.,  2969.],
       [   59.,   179.,   359.,   599.,   899.,  1259.,  1679.,  2159.,
         2699.,  3299.]])

la cual se puede escribir también como

In [47]:
a *= 3  # equivalente a np.multiply(b,3,b)
a -= 1  # equivalente a np.subtract(b,1,b)

note que por el uso del operador `=` el array `b` es una referencia al array `a`, por lo tanto las operaciones anteriores también modifican al array `a`. Para evitar esto se debe asignar a `b` una copia de `a`: `b=a.copy()`  

In [46]:
b = a.copy()
b *= 3  # equivalente a np.multiply(b,3,b)
b -= 1  # equivalente a np.subtract(b,1,b)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]] False


In [48]:

print b == a, b is a

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]] False


---
### Ejercicio

Compare el tiempo de ejecución para las operación `b = 3*a-1` y
```python
b = a
b *= 3  # equivalente a np.multiply(b,3,b)
b -= 1  # equivalente a np.subtract(b,1,b)
```

In [3]:
import numpy as np
import time

a = np.empty((1000,1000))

t0 = time.time()
b = a.copy()

for i in xrange(0,a.shape[0]):
    for j in xrange(0,a.shape[1]):
        b[i,j] = 3*b[i,j]-1
    
t1 = time.time()

b = a
b *= 3  # equivalente a np.multiply(b,3,b)
b -= 1  # equivalente a np.subtract(b,1,b)

t2 = time.time()

print 'ciclos:',t1-t0
print 'numpy:', t2-t1

ciclos: 1.90904307365
numpy: 0.00336098670959


---

Los siguientes operadores ofrecen aritmética `in-place` para arrays:
```python
a *= 3.     # multiplica los elementos de a por 3
a += 1.     # suma 1 a los elementos de a
a -= 1.     # resta 1 a los elementos de a
a /= 3.     # divide cada elemento de a por 2
a **= 2.    # eleva al cuadrado cada elemento de a
```

Existen también funciones trigonométicas que pueden ser o bien aplicadas a escalares o también a arrays de python:
```python
c = np.sin(b)
c = np.arcsin(b)
c = np.sinh(b)
```
similarmente para la familia del coseno y la tangente. Si `b` es un array la función `np.sin(b)` retornará un array de la misma dimensión para el cual sus elementos son los valores de la función `np.sin` evaluados para cada elemento de `b`.

Otras operaciones son
```python
c = b**2.5
c = np.log(b)
c = np.exp(b)
c = np.sqrt(b)
```

**Pregunta:** ¿Se obtiene el mismo resultado para un array `a` si usamos `a **= 2.5` o `a=a**2.5`?

In [4]:
func = lambda i,j: (i+1)*(j+1)*(j+2)   # función que retorna la operación con los índices i,j
a = np.fromfunction(func,(100,100))

b = a.copy()
b **= 2.5

c = a.copy()
c = c**2.5

c == b

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ..., 
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)

---
### Ejercicio

Consideremos la matrix `a` de dimensión 5x4 que contiene números enteros de manera aleatoria
```python
a = np.arange(0,20)
np.random.seed(10)   # fija la semilla
np.random.shuffle(a) # modificación in-place de a
a.shape = (5,4)      # redimensionamos a una matriz 5x4
```
encuentre el valor máximo guardado en el array `a` y además su ubicación (índices) `i`,`j`.

In [41]:
#a = np.arange(0,20)
#np.random.seed(np.random.randint(0,100))   # fija la semilla
#np.random.shuffle(a) # modificación in-place de a
#a.shape = (5,4)      # redimensionamos a una matriz 5x4

a = np.random.rand(5,4)

mayor = 0
for i in xrange(0,a.shape[0]):
    for j in xrange(0,a.shape[1]):
        if mayor < a[i,j]:
            mayor = a[i,j]
            pos = (i,j)

print a
print mayor
print pos

[[ 0.21418452  0.48377777  0.4664515   0.64147676]
 [ 0.63884634  0.89204127  0.66773516  0.7320433 ]
 [ 0.65517064  0.29611062  0.52765692  0.28062458]
 [ 0.81800681  0.96262976  0.63734574  0.09596636]
 [ 0.62398468  0.78578178  0.64027498  0.38163384]]
0.962629760489
(3, 1)


In [47]:
a.max()

0.96262976048919868

---

Numpy ofrece métodos para encontrar máximos y mínimos dentro de arrays. El método `a.argmax()` entrega el índice donde su ubica el elemento más grande de `a`, similarmente para `a.argmin()`; por el contrario `a.max()` y `a.min()` retornan el valor máximo y mínimo respectivamente.

Una estadística simple se puede realizar sobre los elementos del array con los métodos `a.mean()`, `a.var()`, `a.std()`, `a.median()`. La suma de todos los elementos de un array se puede encontrar como `np.sum(a)`.

---

### Ejercicio: Integrales definidas y el método del rectángulo

(ver [wikipedia](https://en.wikipedia.org/wiki/Rectangle_method))

El método del rectángulo calcula de manera aproximada una integra definida de una funcíon. Una integral en un intervalo definido
$$
\int_a^b f(x) \mathrm{d}x
$$
puede verse como el área bajo la curva dibujada por la función en el integrando.

<img src="definite-integral.png">

Una aproximación al valor numérico de la integral se puede lograr dividiendo el área bajo la curva en rectángulos para los cuales su área puede ser calculada.

<img src="rectangle_rule.gif">

La aproximación a la integral será entonces la suma de estas pequeñas áreas que se encuentran en el intervalo de integración.

Especificamente, el método del rectangulo para la integral $\int_a^b f(x) \mathrm{d}x$ se formula de la siguiente manera: se divide el intervalo de integración $(a,b)$ en $N$ segmentos iguales de longitud $h=(b-a)/N$, con estos se define un rectangulo de altura $f(x_n)$ y base $h$ y área $A_n = h\, f(x_n)$ donde $x_n=a+n\,h$, de manera que la integral se puede aproximar como 
$$
\int_a^b f(x) \mathrm{d}x \approx \sum_{n=0}^{N-1} h\, f(x_n) = \sum_{n=0}^{N-1} A_n
$$

1. Aproxime la integral
$$
\int_0^{\pi/2} \sin(x) \mathrm{d}x 
$$
haciendo uso del método del rectángulo.