# Clase 21

## Numpy

Numpy (de *NUMerical PYthon*) es un paquete de Python que presenta algunas mejoras para el procesamiento de datos in ciencias computacionales; este ofrece un desempeño parecido al de los lenguajes compilados (C, C++, FORTRAN) pero con la facilidad de la sintaxis de Python. Numpy define **arrays** (type ndarray) que continene el mismo tipo de datos y de un tamaño fijo determinado al momento de su creación, ofreciendo operaciones más eficientes sobre ellos que las realizadas sobre listas a través de los bucles `for`. 

Toda la documentación de Numpy puede ser encontrada en la red junto con algunos ejemplos:
- [Numpy User Guide](http://docs.scipy.org/doc/numpy/user/index.html)
- [Cookbook](http://scipy.github.io/old-wiki/pages/Cookbook.html)

Para usar Numpy es común usar
```Python
from numpy import *
```
o, de otra forma,
```Python
import numpy as np
```

¿Cuál es la diferencia entre las dos formas anteriores?

In [1]:
import numpy as np

### Creando Arrays de Numpy

Los arrays de numpy se pueden crear de varias maneras. Algunas de las más comunes son las siguientes:

Crear un array de una longitud especificada lleno de ceros

In [9]:
np.zeros?

In [3]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [4]:
np.zeros( (4,3) )    # (filas,columnas)=(axis 0, axis 1)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
# Array tres-dimensional
a = np.zeros( (4,3,2) )    # (filas,columnas,profundidad)=(axis 0, axis 1,axis 2)

In [8]:
print a

[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


<img src="anatomyarray.png"\>

Por defecto `np.zeros` genera elementos de tipo `float`. Con el segundo argumento `dtype` (data type) definido como `int`, `complex`, `int16` o `bool`, otros tipos de elementos se pueden generar. 

In [10]:
np.zeros((2,2),bool)

array([[False, False],
       [False, False]], dtype=bool)

In [11]:
np.zeros((2,2),dtype=bool)

array([[False, False],
       [False, False]], dtype=bool)

In [12]:
np.zeros((2,2),complex)

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]])

In [13]:
np.zeros((2,2),int)

array([[0, 0],
       [0, 0]])

El atributo `shape` de un objeto `ndarray` retorna una tupla indicando el número de elementos en cada uno de los axis del array.

In [14]:
a = np.zeros( (4,3,2) ) 
a.shape

(4, 3, 2)

También existe la función correspondiente `np.ones` que nos retorna un array con valores de uno

In [17]:
np.ones( (3,4,5) )

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [18]:
np.ones( (3,4,5), dtype=complex )

array([[[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j]],

       [[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j]],

       [[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
        [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j]]])

In [19]:
np.ones( (3,4,5), dtype=bool )

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]], dtype=bool)

### Copiando arrays de numpy

Si queremos crear un array `r` con el mismo tamaña y elementos del mismo tipo (`dtype`) que un array `x`, podemos 

In [20]:
x = np.ones((10,10), dtype=complex)
r = x.copy()

In [21]:
x.shape

(10, 10)

In [22]:
print r.shape

(10, 10)


In [23]:
print type(r)

<type 'numpy.ndarray'>


In [24]:
print r.dtype.name

complex128


In [32]:
r == x

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [29]:
r=x

In [30]:
r

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1

In [31]:
r is x

True

o podemos crear una matrix de ceros con el tamaño y tipo de `x`

In [27]:
r = np.zeros(x.shape,dtype=x.dtype.name)

In [33]:
r

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j,  1

sin embargo existe una forma más fácil de lograr esto. Las funciones `np.empty_like`, `np.zeros_like`, `np.ones_like` (también llamadas *look-alike constructors*) toman por argumento un array y crean uno con entradas vacías, ceros y unos; respectivamente.

In [34]:
np.empty_like?

In [35]:
r = np.empty_like(x)

In [36]:
print r

[[  4.04738577e-320 +2.01578784e-321j   0.00000000e+000 +2.23004158e-316j
    4.94065646e-324 +2.23005857e-316j   4.94065646e-324 +2.23004316e-316j
    2.41907520e-312 +6.93934856e-310j   2.35541533e-312 +7.21478569e-313j
    7.21478569e-313 +2.44029516e-312j   4.94065646e-324 +2.56761491e-312j
    6.93934614e-310 +1.23075756e-312j   2.14321575e-312 +2.14321575e-312j]
 [  2.48273508e-312 +8.48798316e-314j   2.22809558e-312 +2.23004592e-316j
    6.93934101e-310 +9.33678148e-313j   2.31297541e-312 +2.18565567e-312j
    8.48798316e-314 +4.94065646e-324j   2.23005225e-316 +9.88131292e-323j
    6.93934856e-310 +1.20953760e-312j   6.93934856e-310 +2.07955588e-312j
    1.14587773e-312 +3.81959242e-313j   0.00000000e+000 +0.00000000e+000j]
 [  2.05833592e-312 +2.23004869e-316j   2.23005146e-316 +2.23005501e-316j
    0.00000000e+000 +0.00000000e+000j   8.48798316e-314 +2.05833592e-312j
    2.23004237e-316 +2.23005581e-316j   2.50395503e-312 +2.41907520e-312j
    4.94065646e-324 +2.33419537e-312

In [41]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Arrays con una secuencia de números

La función `np.linspace(start,stop,n)` produce un conjunto de `n` números uniformemente distribuidos comenzando desde `start` y terminando en `stop` (ambos incluídos). Por ejemplo

In [ ]:
np.linspace?

In [42]:
x = np.linspace(-5,5,11)
print x

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [43]:
x = np.linspace(-5,5,21)
print x

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.
  2.5  3.   3.5  4.   4.5  5. ]


In [44]:
x = np.linspace(-5,5,41)
print x

[-5.   -4.75 -4.5  -4.25 -4.   -3.75 -3.5  -3.25 -3.   -2.75 -2.5  -2.25
 -2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75
  4.    4.25  4.5   4.75  5.  ]


In [46]:
x = np.linspace(-5,5,54)
print x

[-5.         -4.81132075 -4.62264151 -4.43396226 -4.24528302 -4.05660377
 -3.86792453 -3.67924528 -3.49056604 -3.30188679 -3.11320755 -2.9245283
 -2.73584906 -2.54716981 -2.35849057 -2.16981132 -1.98113208 -1.79245283
 -1.60377358 -1.41509434 -1.22641509 -1.03773585 -0.8490566  -0.66037736
 -0.47169811 -0.28301887 -0.09433962  0.09433962  0.28301887  0.47169811
  0.66037736  0.8490566   1.03773585  1.22641509  1.41509434  1.60377358
  1.79245283  1.98113208  2.16981132  2.35849057  2.54716981  2.73584906
  2.9245283   3.11320755  3.30188679  3.49056604  3.67924528  3.86792453
  4.05660377  4.24528302  4.43396226  4.62264151  4.81132075  5.        ]


Como este comando es de uso común existe una sintaxis compacta para su uso `np.r_[start:stop:incj]` (note que el paso se especifíca como un número imaginario con un `j` en el final):

In [47]:
a = np.r_[-5:5:11j]    # equivalente a np.linspace(-5,5,11)
print a

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


Si en vez de especificar el número de elementos en el array usted desea espcificar el incremento entre los números de la secuencia puede usar entonces las función `np.arange`

In [48]:
np.arange?

In [52]:
x = np.arange(-5,5,1,float)
print x

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]


Note que el límite superior del intervalo no aparece en la lista, esto debido a que `np.arange` funciona como `range` o `xrange`. Desafortunadamente la función `np.arrange` padece de algunos errores de redondeo que pueden generar complicaciones, para evitarlos se recomienda usar `np.linspace`.

La sintaxis compacta para `np.arange` se define como `np.r_[start:stop:step]` (note la ausencia de `j`)

In [53]:
a = np.r_[-5:5:1]    # equivalente a np.arange(-5,5,1)
print a

[-5 -4 -3 -2 -1  0  1  2  3  4]


### Construccion de arrays desde listas de Python

La función `array` contruye un array desde una lista de python

In [54]:
L = [1.2,3,.6,-3,7j]
print type(L)

<type 'list'>


In [55]:
np.array?

In [56]:
a = np.array(L)
print a

[ 1.2+0.j  3.0+0.j  0.6+0.j -3.0+0.j  0.0+7.j]


In [57]:
print type(a)

<type 'numpy.ndarray'>


de igual manera, dado que no todas las funcionalidades de las listas existen para los arrays, se puede convertir un array en una lista

In [58]:
L1 = a.tolist()
print L1

[(1.2+0j), (3+0j), (0.6+0j), (-3+0j), 7j]


In [59]:
print type(L1)

<type 'list'>


### Cambiando las dimensiones de un array

Un array tiene un tamaño fijo en memoria, determinado por el número de elementos que contiene y su tipo, por ejemplo el array

In [60]:
y = np.zeros((100,100,100),dtype=complex)

In [61]:
y.ndim   # número de dimensiones

3

In [62]:
y.shape # (axis0, axis1, axis2)

(100, 100, 100)

In [63]:
len(y.shape) # número de dimensiones

3

contiene `y.size` elementos, o también `np.size(y)` elementos

In [64]:
y.size    # número total de elementos

1000000

In [65]:
np.size(y)   # número total de elementos

1000000

In [66]:
y.shape[0]*y.shape[1]*y.shape[2]   # número total de elementos

1000000

Usar la función `len(y)` nos daría simplemente la longitud de la primera dimensión, tal y como si lo estuvieramos usando sobre una lista de python.

En memoria el array ocupa

In [67]:
y.nbytes

16000000

que es diferente al espacio que ocuparía un array con elementos booleanos

In [68]:
z = np.zeros((100,100,100),dtype=bool)
z.nbytes

1000000

Es posible cambiar el tamaño de un array a través del método `reshape` (el cual retorna una matriz con las dimensiones deseadas) o el atributo `shape` (que modifica la matriz misma según sea requerido)

In [72]:
a = np.array([1.2,3,.6,-3])
a.shape
print a

[ 1.2  3.   0.6 -3. ]


In [70]:
a.shape = (2,2)    # convertir el array en una matriz 2x2
print a.shape
print a

(2, 2)
[[ 1.2  3. ]
 [ 0.6 -3. ]]


In [71]:
a = a.reshape(4,1)    # convierte el array en una columa
print a.shape
print a

(4, 1)
[[ 1.2]
 [ 3. ]
 [ 0.6]
 [-3. ]]


El método `ravel` nos convierte cualquier array en uno de una dimensión

In [74]:
a.shape = (2,2)    # convertir el array en una matriz 2x2
a.ravel()

array([ 1.2,  3. ,  0.6, -3. ])

### Inicializando un array con una función de python

Es posible hace una función que mapee los índices de un array a un valor que será guardado en a posición indicada por los índices y usar esta función para incializar un array

In [75]:
def func(i,j):
    return (i+1)*(j+4-i)

# Construir un array 3x6 donde a[i,j] = func(i,j)
a = np.fromfunction(func, (3,6))

print a

[[  4.   5.   6.   7.   8.   9.]
 [  6.   8.  10.  12.  14.  16.]
 [  6.   9.  12.  15.  18.  21.]]


In [76]:
f = lambda i, j: i == j
np.fromfunction(f, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]], dtype=bool)

### Indexación de arrays

En una dimensión los arrays de numpy siguen la misma sintaxis que las listas

In [77]:
a = np.linspace(-1,1,6)
print a

[-1.  -0.6 -0.2  0.2  0.6  1. ]


In [78]:
a[2:4] = -1      # Asigna -1 al los elementos a[2] y a[3]
print a

[-1.  -0.6 -1.  -1.   0.6  1. ]


In [79]:
a[0] = a[-1]     # Primer elemento igual al último
print a

[ 1.  -0.6 -1.  -1.   0.6  1. ]


In [80]:
a[:] = 0         # Todos los elemtos iguales a cero
print a

[ 0.  0.  0.  0.  0.  0.]


In [ ]:
a.fill(3)        # Todos los elementos iguales a 3
print a

Una sintaxis extendida es ofrecidad para arrays de múltiples dimensiones

In [81]:
a.shape = (2,3)    # convierte  a en una matriz 2x3
print a

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [82]:
print a[0,1]       # accede al elemento (0,1)

0.0


In [83]:
a[1,2] = 10       # asigna 10 al elemento (1,2)
print a

[[  0.   0.   0.]
 [  0.   0.  10.]]


In [84]:
a[0][2] = 6       # asigna 10 al elemento (0,2)
print a

[[  0.   0.   6.]
 [  0.   0.  10.]]


In [85]:
a.itemset( (1,1), 5 ) # asigna 5 al elemento (1,1)
# esta forma es más rápida que las anteriores
print a

[[  0.   0.   6.]
 [  0.   5.  10.]]


In [87]:
print a[:,1]      # imprime la columna de índice 1

[ 0.  5.]


In [88]:
print a[0,:]      # imprime la fila de índice 0

[ 0.  0.  6.]


In [89]:
a[:,:] = 0        # asigna 0 a todos los elementos
print a

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


En general los índices tienen la forma `start:stop:step`, indicando todos los elementos desde `start` hasta `stop-step` en pasos de `step`. Estos índices en general se respresentan como *slices*

In [90]:
a = np.linspace(0,29,30)
a.shape = (5,6)
a

array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.,  16.,  17.],
       [ 18.,  19.,  20.,  21.,  22.,  23.],
       [ 24.,  25.,  26.,  27.,  28.,  29.]])

In [91]:
a[1:3,:-1:2]     # a[i,j] para i=1,2 y j=0,2,4   

array([[  6.,   8.,  10.],
       [ 12.,  14.,  16.]])

In [92]:
a[::3,2:-1:2]    # a[i,j] para i=0,3 y j=2,4

array([[  2.,   4.],
       [ 20.,  22.]])

In [93]:
i = slice(None, None, 3); j = slice(2, -1, 2)
print i
print j

slice(None, None, 3)
slice(2, -1, 2)


In [94]:
a[i,j]

array([[  2.,   4.],
       [ 20.,  22.]])

**NOTA:** En caso contrario a las listas de python, el slicing de arrays de numpy da una referencia al array y no una copia del mismo; por lo tanto, si una referencia se modifica, el array mismo se modifica también.

In [102]:
print a

[[ 55.   1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.  11.]
 [ 12.  13.  14.  15.  16.  17.]
 [ 18.  19.  20.  21.  22.  23.]
 [ 24.  25.  26.  27.  28.  29.]]


In [103]:
col0 = a[:,0].copy()
print col0

[ 55.   6.  12.  18.  24.]


In [104]:
col0[0] = 0

In [105]:
col0

array([  0.,   6.,  12.,  18.,  24.])

In [106]:
a

array([[ 55.,   1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.,  16.,  17.],
       [ 18.,  19.,  20.,  21.,  22.,  23.],
       [ 24.,  25.,  26.,  27.,  28.,  29.]])

Cualquier lista o array puede ser usada como un índice . Por ejemplo, el slice `a[f,t,i]` es equivalente a `a[rage(f:t:i)]`. Un array `b` con valores booleanos también puede usarse como índice; los índices setán entonces aquellos en `b` para los cuales su valor es verdadero, es decir, expresiones booleanas pueden usarse como índices `a[a>0]`.

In [107]:
a = np.linspace(1,8,8)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [108]:
a[[1,6,7]] = 10
a

array([  1.,  10.,   3.,   4.,   5.,   6.,  10.,  10.])

In [109]:
a[range(2,8,3)] = -2
a

array([  1.,  10.,  -2.,   4.,   5.,  -2.,  10.,  10.])

In [110]:
a<0

array([False, False,  True, False, False,  True, False, False], dtype=bool)

In [111]:
a[a<0]

array([-2., -2.])

In [112]:
a[a>0]

array([  1.,  10.,   4.,   5.,  10.,  10.])

In [113]:
a[a<0] = a.max()
a

array([  1.,  10.,  10.,   4.,   5.,  10.,  10.,  10.])

In [114]:
a[a<0]

array([], dtype=float64)